=== MobSF/Mobile-Security-Framework-MobSF/DynamicAnalyzer/tools/tshark/wimaxasncp/dictionary.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- $Id$ -->

<!ELEMENT dictionary (tlv+)>

<!ELEMENT tlv (enum*)>
<!ATTLIST tlv
    name    CDATA #REQUIRED
    type    CDATA #REQUIRED
    decoder CDATA #IMPLIED
    since CDATA #IMPLIED
>

<!ELEMENT enum EMPTY>
<!ATTLIST enum
    name CDATA #REQUIRED
    code CDATA #REQUIRED
>

=== MobSF/Mobile-Security-Framework-MobSF/DynamicAnalyzer/tools/tshark/wimaxasncp/dictionary.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- $Id$ -->

<!DOCTYPE dictionary SYSTEM "dictionary.dtd">

<!-- WiMax ASN R6 message disection specification. -->
<!-- Supports following NWG versions: -->
<!-- 0 - NWG R1.0 V1.0.0 -->
<!-- 1 - NWG R1.0 V1.2.0 -->
<!-- 2 - NWG R1.0 V1.2.1 -->

<dictionary>

    <!-- ****************************************************************** -->

    <tlv name="Accept/Reject Indicator"
         type="1"
         decoder="WIMAXASNCP_TLV_ENUM8">

        <enum name="accept"
              code="0x00"/>

        <enum name="reject"
              code="0x01"/>
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="Accounting Extension"
         type="2"
         decoder="WIMAXASNCP_TLV_BYTES">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="Action Code"
         type="3"
         decoder="WIMAXASNCP_TLV_ENUM16">

        <enum name="Deregister MS"
              code="0x0000"/>

        <enum name="Suspend all MS traffic"
              code="0x0001"/>

        <enum name="Suspend user traffic"
              code="0x0002"/>

        <enum name="Resume traffic"
              code="0x0003"/>

        <enum name="Reserved (was: MS terminate current normal operations with BS)"
              code="0x0004"/>

        <enum name="MS shall be put into idle mode"
              code="0x0005"/>

        <enum name="Initial Authentication Failure"
              code="0xFFFE"/>

        <enum name="MS shall be sent the RES-CMD by the BS"
              code="0xFFFF"/>
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="Action Time"
         type="4"
         decoder="WIMAXASNCP_TLV_DEC32">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="AK"
         type="5"
         decoder="WIMAXASNCP_TLV_BYTES">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="AK Context"
         type="6"
         decoder="WIMAXASNCP_TLV_COMPOUND">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="AK ID"
         type="7"
         decoder="WIMAXASNCP_TLV_BYTES">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="AK Lifetime"
         type="8"
         decoder="WIMAXASNCP_TLV_DEC16">
    </tlv>

    <tlv name="AK Lifetime"
         type="8"
         decoder="WIMAXASNCP_TLV_DEC32"
	 since="1">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="AK SN"
         type="9"
         decoder="WIMAXASNCP_TLV_HEX8">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="Anchor ASN GW ID / Anchor DPF Identifier"
         type="10"
         decoder="WIMAXASNCP_TLV_ID">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="Anchor MM Context"
         type="11"
         decoder="WIMAXASNCP_TLV_COMPOUND">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="Anchor PCID - Anchor Paging Controller ID"
         type="12"
         decoder="WIMAXASNCP_TLV_ID">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="Anchor PC Relocation Destination"
         type="13"
         decoder="WIMAXASNCP_TLV_ID">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="Anchor PC Relocation Request Response"
         type="14"
         decoder="WIMAXASNCP_TLV_ENUM8">

        <enum name="Accept"
              code="0x00"/>

        <enum name="Refuse"
              code="0x01"/>
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="Associated PHSI"
         type="15"
         decoder="WIMAXASNCP_TLV_DEC8">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="Anchor Authenticator ID"
         type="16"
         decoder="WIMAXASNCP_TLV_ID">
    </tlv>

    <tlv name="FA Revoke Reason"
         type="16"
         decoder="WIMAXASNCP_TLV_ENUM8"
	 since="1">

        <enum name="DHCP Release"
              code="0x00"/>

        <enum name="DHCP expiry"
              code="0x01"/>

        <enum name="FA initiated release"
              code="0x02"/>

        <enum name="HA initiated release"
              code="0x03"/>
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="Authentication Complete"
         type="17"
         decoder="WIMAXASNCP_TLV_COMPOUND">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="Authentication Result"
         type="18"
         decoder="WIMAXASNCP_TLV_ENUM8">

        <enum name="Success"
              code="0x00"/>

        <enum name="Failure"
              code="0x01"/>
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="Authenticator Identifier"
         type="19"
         decoder="WIMAXASNCP_TLV_ID">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name=" Auth-IND"
         type="20"
         decoder="WIMAXASNCP_TLV_DEC8">
    </tlv>

    <tlv name="RRQ"
         type="20"
         decoder="WIMAXASNCP_TLV_BYTES"
	 since="1">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="Authorization Policy"
         type="21"
         decoder="WIMAXASNCP_TLV_BITFLAGS16">

        <enum name="RSA authorization"
              code="WIMAXASNCP_BIT16(15)"/>

        <enum name="EAP authorization"
              code="WIMAXASNCP_BIT16(14)"/>

        <enum name="Authenticated-EAP authorization"
              code="WIMAXASNCP_BIT16(13)"/>

        <enum name="HMAC supported"
              code="WIMAXASNCP_BIT16(12)"/>

        <enum name="CMAC supported"
              code="WIMAXASNCP_BIT16(11)"/>

        <enum name="64-bit Short-HMAC"
              code="WIMAXASNCP_BIT16(10)"/>

        <enum name="80-bit Short-HMAC"
              code="WIMAXASNCP_BIT16(9)"/>

        <enum name="96-bit Short-HMAC"
              code="WIMAXASNCP_BIT16(8)"/>
    </tlv>

    <tlv name="Authorization Policy"
         type="21"
         decoder="WIMAXASNCP_TLV_BITFLAGS8"
	 since="1">

        <enum name="RSA-based authorization at the initial network entry"
              code="WIMAXASNCP_BIT8(7)"/>

        <enum name="EAP-based authorization at the initial network entry"
              code="WIMAXASNCP_BIT8(6)"/>

        <enum name="Authenticated EAP-based authorization at the initial network entry"
              code="WIMAXASNCP_BIT8(5)"/>

        <enum name="Reserved (was: HMAC supported)"
              code="WIMAXASNCP_BIT8(4)"/>

        <enum name="RSA-based authorization at reentry"
              code="WIMAXASNCP_BIT8(3)"/>

        <enum name="EAP-based authorization at reentry"
              code="WIMAXASNCP_BIT8(2)"/>

        <enum name="Authenticated EAP-based authorization at reentry"
              code="WIMAXASNCP_BIT8(1)"/>

        <enum name="Reserved"
              code="WIMAXASNCP_BIT8(0)"/>
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="Available Radio Resource DL"
         type="22"
         decoder="WIMAXASNCP_TLV_DEC8">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="Available Radio Resource UL"
         type="23"
         decoder="WIMAXASNCP_TLV_DEC8">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="BE Data Delivery Service"
         type="24"
         decoder="WIMAXASNCP_TLV_COMPOUND">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="BS ID"
         type="25"
         decoder="WIMAXASNCP_TLV_ID">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="BS Info"
         type="26"
         decoder="WIMAXASNCP_TLV_COMPOUND">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="BS-originated EAP-Start Flag"
         type="27"
         decoder="WIMAXASNCP_TLV_FLAG0">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="Care-Of Address (CoA)"
         type="28"
         decoder="WIMAXASNCP_TLV_IPV4_ADDRESS">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="CID"
         type="29"
         decoder="WIMAXASNCP_TLV_DEC16">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="Classification Rule"
         type="30"
         decoder="WIMAXASNCP_TLV_COMPOUND">
    </tlv>

    <tlv name="Classification Rule Index"
         type="30"
         decoder="WIMAXASNCP_TLV_DEC16"
	 since="1">
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="Classification Rule Action"
         type="31"
         decoder="WIMAXASNCP_TLV_ENUM8">

        <enum name="Add Classification Rule"
              code="0"/>

        <enum name="Replace Classification Rule"
              code="1"/>

        <enum name="Delete Classification Rule"
              code="2"/>
    </tlv>

    <!-- ****************************************************************** -->

    <tlv name="Classification Rule Priority"
         type="32"
         decoder="WIMAXASNCP_TLV_DEC8">
    </tlv>
